# .github/workflows/tests.yml
name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Sanity check (optional)
        run: |
          python -c "import sys, os; print('workspace=', os.getcwd()); print('has src=', os.path.isdir('src')); print('sys.path[0]=', sys.path[0])"

      - name: Run tests
        run: pytest -q
